name: Abacus
version: 1.2.0
author: Feaelin <iain@ruhlendavis.org>
description: Offers ability to perform calculations while in Minecraft
website: http://dev.bukkit.org/server-mods/abacus/
# Source: https://github.com/LostMC/Abacus

main: org.lostmc.abacus.Abacus

commands:
  abacus:
    description: Do math inside of Minecraft!
    permission: abacus.abacus
    permission-message: "§cYou do not have access to that command."
permissions:
  abacus.*:
    description: Access for all abacus commands.
    default: op
  abacus.abacus:
    description: Allows the use of the abacus command.
    default: true
