name: Abacus
version: 0.0.0
author: Feaelin <feaelin@kemenel.org>
description: Offers ability to perform calculations while in Minecraft

main: org.ruhlendavis.mc.abacus.Abacus

commands:
  abacus:

permissions:
