name: Abacus
version: 0.9.1
author: Feaelin <iain@ruhlendavis.org>
description: Offers ability to perform calculations while in Minecraft

main: org.ruhlendavis.mc.abacus.Abacus

commands:
  abacus:
    description: Do math inside of Minecraft!
    permission: abacus.abacus
    permission-message: "§cYou do not have access to that command."
permissions:
  abacus.*:
    description: Access for all abacus commands.
    default: op
  abacus.abacus:
    description: Allows the use of the abacus command.
    default: true
